# Generated by Django 4.0.6 on 2022-07-14 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mains', 'JEE Main')], default='mains', max_length=50)),
                ('gender', models.CharField(choices=[('Gender-Neutral', 'Male'), ('Female-only (including Supernumerary)', 'Female')], default='M', max_length=50)),
                ('percentile', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('catagory', models.CharField(choices=[('OPEN', 'OPEN'), ('OPEN (PwD)', 'OPEN (PwD)'), ('EWS', 'EWS'), ('EWS (PwD)', 'EWS (PwD)'), ('OBC-NCL', 'OBC-NCL'), ('OBC-NCL (PwD)', 'OBC-NCL (PwD)'), ('SC', 'SC'), ('SC (PwD)', 'SC (PwD)'), ('ST', 'ST'), ('ST (PwD)', 'ST (PwD)')], default='OPEN', max_length=15)),
                ('catagory_rank', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
