# Generated by Django 4.0.6 on 2022-07-14 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcolleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranktable',
            name='advanced_catagory_rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ranktable',
            name='advanced_general_rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
