# Generated by Django 4.0.6 on 2022-07-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listcolleges', '0002_ranktable_advanced_catagory_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranktable',
            name='title',
        ),
    ]
